GET http://localhost:8080/product/get_page/1
Content-Type: application/json

//{
//  "id": 6,
//  "localeDate": "2020-09-01",
//  "customerId": 4,
//  "productId": [20]
//}

//{
//  "id": 28,
//  "title": "meat",
//  "price": 1.0,
//  "sellerId": 1,
//  "orderId": 2
//}

###