PUT http://localhost:8080/order/update
Content-Type: application/json

{
  "id": 1,
  "localeDate": "2020-09-01",
  "customerId": 2,
  "productId": [7,8]
}

//{
//  "id": 5,
//  "title": "meat",
//  "price": 9.0,
//  "sellerId": 1,
//  "orderId": null
//}

###